#!/bin/sh
#
# Checks for TODO_$USERNAME in changed files and untracked files.
#
# Allows developers to add tasks to files that need to be fixed before
# committing by adding comments containing TODO_$USERNAME.

found=0

# Check changes
for f in `git diff --name-only`; do
    git diff $f | grep -q "\sTODO_$USERNAME:\s"

    if [ $? -eq 0 ]; then
        found=1
        echo "TODO_$USERNAME found in: $f"
    fi
done

# Check untracked
for f in `git ls-files --others --exclude-standard`; do
    grep -q "\sTODO_$USERNAME:\s" $f

    if [ $? -eq 0 ]; then
        found=1
        echo "TODO_$USERNAME found in: $f"
    fi
done

if [ $found -eq 1 ]; then
    exit 1
else
    exit 0
fi
